name: blog.ryan.ec
title: blog.ryan.ec
url: https://blog.ryan.ec
description: strongly worded opinions about computering and other such nonsense
permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
twitter_username: ryancragun
github_username: ryancragun
gems:
  - jekyll-sitemap
